#!/usr/bin/perl

($input,$config)=@ARGV;

$input='Makefile.in' if $input eq '';
$config='conf/migdal.conf' if $config eq '';

open OUT,'>Makefile';
print OUT "# Created automatically from Makefile.in\n";
open IN,$input;
while(<IN>)
     {
     unless(/^#\s@\(#\)\s\$Id[^\$]*\$/)
           {
           print OUT;
	   next;
	   }
     open CONF,$config;
     while(<CONF>)
	  {
	  next if /\?>/ || /<\?/;
	  s/#.*$//;
	  next if /^\s*$/;
	  my ($name,$value)=/^\$(\w+)=(.*);\s*$/;
	  print OUT "$name=$value\n";
	  }
     close CONF;
     }
close IN;
close OUT;
