#!/usr/bin/perl

# @(#) $Id$

sub stripComment
{
my ($s)=@_;

my $quoted=0;
my $pos=0;
while($pos<length($s))
     {
     $quoted=1-$quoted if substr($s,$pos,1) eq "'" || substr($s,$pos,1) eq '"';
     last if !$quoted && substr($s,$pos,1) eq '#';
     $pos++;
     }
return substr($s,0,$pos);
}

($input,$config)=@ARGV;

$input='Makefile.in' if $input eq '';
$config='conf/migdal.conf' if $config eq '';
$status=0;

print "# Created automatically from Makefile.in\n";
open IN,$input;
while(<IN>)
     {
     unless(/^#\s@\(#\)\s\$Id[^\$]*\$/)
           {
           print;
	   next;
	   }
     open CONF,$config;
     while(<CONF>)
	  {
	  next if /\?>/ || /<\?/ || /^\s*require/;
	  $_=stripComment($_);
	  next if /^\s*$/;
	  my ($name,$value)=/^\$(\w+)=(.*);\s*$/;
	  if($name eq '' || $value eq '')
	    {
	    print STDERR "confmake: Incorrect config line $.: $_";
	    $status=1;
	    }
	  else
	    {
	    print "$name=$value\n";
	    }
	  }
     close CONF;
     }
close IN;
exit $status;
