#!/usr/bin/perl

exit unless defined $ARGV[0];
$rname = $varname = $ARGV[0];
$rname =~ s/_([a-z])/'_'.uc($1)/ge;
$rname = ucfirst $rname;
$rname =~ s/_//g;
print <<EOT
    public function get$rname() {
        return \$this->$varname;
    }
EOT
