ALTER TABLE `forums` CHANGE `up` `parent_id` INT(11) DEFAULT '0' NOT NULL;
ALTER TABLE `messages` ADD `up` INT NOT NULL AFTER `id`, ADD `track` VARCHAR(255) NOT NULL AFTER `up`;
ALTER TABLE `messages` ADD INDEX (`up`, `track`);
update version set db_version=2;
DROP TABLE `choices`;
DROP TABLE `complain_scripts`;
DROP TABLE `complain_types`;
ALTER TABLE `complains` ADD `no_auto` TINYINT NOT NULL;
ALTER TABLE `users` ADD `name_sort` VARCHAR(60) NOT NULL AFTER `name`;
ALTER TABLE `users` ADD INDEX (`name_sort`);
ALTER TABLE `users` ADD `jewish_name_sort` VARCHAR(60) NOT NULL AFTER `jewish_name`;
ALTER TABLE `users` ADD INDEX (`jewish_name_sort`);
ALTER TABLE `users` ADD `surname_sort` VARCHAR(60) NOT NULL AFTER `surname`;
ALTER TABLE `users` ADD INDEX (`surname_sort`);
ALTER TABLE `messages` ADD `url_domain` VARCHAR(70) NOT NULL AFTER `sent`;
ALTER TABLE `messages` ADD INDEX (`url_domain`);
ALTER TABLE `messages` ADD `topic_link` INT NOT NULL AFTER `sent`;
ALTER TABLE `messages` ADD `url_check` DATETIME NOT NULL, ADD `url_check_success` DATETIME NOT NULL;
ALTER TABLE `messages` ADD INDEX (`url_check`, `url_check_success`); 
ALTER TABLE `messages` ADD `lang` CHAR(5) NOT NULL AFTER `track`;
