<?php
# @(#) $Id$

define('SELECT_GENERAL',0);
define('SELECT_LARGE_BODY',1);
define('SELECT_CTR',2);
define('SELECT_TOPICS',4);
define('SELECT_INFO',8);
define('SELECT_GRPS',16);
define('SELECT_ALLPOSTING',SELECT_GENERAL|SELECT_LARGE_BODY|SELECT_CTR|
                           SELECT_TOPICS);
define('SELECT_ALLTOPIC',SELECT_GENERAL|SELECT_INFO|SELECT_TOPICS|SELECT_GRPS);
?>
