<?php
# @(#) $Id$

const SELECT_GENERAL = 0;
const SELECT_LARGE_BODY = 1;
const SELECT_CTR = 2;
const SELECT_TOPICS = 4;
const SELECT_INFO = 8;
const SELECT_GRPS = 16;

define('SELECT_ALLPOSTING',
       SELECT_GENERAL | SELECT_LARGE_BODY | SELECT_CTR);
define('SELECT_ALLTOPIC',
       SELECT_GENERAL | SELECT_INFO | SELECT_TOPICS | SELECT_GRPS);
?>
