#!/bin/bash

make || exit 1
for t in $*; do
    echo "Importing $t..." >&2
    echo "delete from $t;"
    echo "\\copy $t from '$t.converted.csv' (format csv, null 'NULL');"
done | psql -d migdal -U migdal -W
