server:
  port: 8081  # Server port

spring:
  # DataSource settings
  datasource:
    url: jdbc:postgresql:migdal?characterEncoding=UTF-8
    username: migdal
    password: migdal
    testWhileIdle: true  # Keep the connection alive if idle for a long time (needed in production)
    validationQuery: SELECT 1

  cache:
    cache-names: >
      users-guestid,
      users-id,
      entries-permsall,
      entries-track,
      entries-catalog,
      entries-id,
      postings-modbitsall

    caffeine:
      spec: maximumSize=500

  jpa:
    show-sql: true  # Show or not log for each sql query
    hibernate:
      ddl-auto: none  # Hibernate DDL auto (create, create-drop, update)
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy  # Naming strategy

    # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
    # stripped before adding them to the entity manager)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect  # The SQL dialect makes Hibernate generate better SQL for the chosen database

  # Mail hub properties
  mail:
    host: smtp.gmail.com
    port: 587
    #username:
    #password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  session:
    store-type: jdbc
    timeout: 2400h  # Session timeout

migdal:
  siteDomain: localhost.localdomain  # Site domain
  subdomains: www,english  # Site subdomains (the first one is default)

  # Maximum period (in hours) of session inactivity. After it elapses, the session is cleared.
  # The short session is opened if user logs in from public computer, the long one - if he logs in from
  # his private computer.
  sessionTimeoutShort: 3
  sessionTimeoutLong: 2400

  # Interval (in hours) of picture grouping. After it elapses, a picture in the same topic by the same user is
  # announced in a new posting.
  publishingInterval: 6

  allowGuests: true  # Allow guest users
  guestLogin: Гость  # Login of guest user

  disableRegister: false  # Disable users' self-registration, allow creation of users by admin only
  regConfirmTimeout: 3  # Timeout (in days) of user e-mail confirmation

  imageDir: /home/smelamud/migdal-images  # Image directory
  imageUrl: /images  # Base image URL
  maxImageSize: 2097152  # Maximal uploaded image size (in bytes)
  imageFileTimeout: 6 # Maximal lifetime (in hours) of an image file not referred from the database

  # Inner image auto-resizing dimensions
  innerImageMaxWidth: 900
  innerImageMaxHeight: 900

  innerImageTimeout: 7 # Maximal lifetime (in days) of an inner image not placed in the article

  # Text cropping parameters for "tiny size"
  tinySize: 64
  tinySizeMinus: 32
  tinySizePlus: 32

  # Text cropping parameters for "small size"
  smallSize: 256
  smallSizeMinus: 128
  smallSizePlus: 128

  # Text cropping parameters for "medium size"
  mediumSize: 1024
  mediumSizeMinus: 512
  mediumSizePlus: 512

  # Text cropping parameters to insert footnotes as tooltips of footnote references
  inplaceSize: 256
  inplaceSizeMinus: 128
  inplaceSizePlus: 128

  # Topic full name maximal size
  topicFullNameEllipSize: 80

  ## Mail service properties

  # Maximum rate of sending mails: <mailSendLimit> mails per <mailSendPeriod> minutes
  mailSendLimit: 10
  mailSendPeriod: 10

  mailFromAddress: mailrobot@migdal.org.ua  # "From:" address of all mails
  mailReplyToAddress: webmaster@migdal.org.ua  # "Reply-To:" address of all mails

  ## Default permissions

  # Virtual "root" topic permissions
  rootTopicUserName: balu
  rootTopicGroupName: balu
  rootTopicPerms: 0x19FF
  rootTopicModbits: 0x0007

  defaultPostingPerms: 0x99FF

  defaultCommentPerms: 0x5557

  # Google reCaptcha keys
  captchaPublicKey: <public key>
  captchaSecretKey: <secret key>

  # Enable HTML caching
  htmlCache: true
