#!/usr/bin/perl

# @(#) $Id$

use DBI;
use Getopt::Long;
Getopt::Long::Configure('no_auto_abbrev','no_ignore_case','bundling');

$VERSION='0.0.1';
$configPath='conf/migdal.conf';
@libpath=();
GetOptions('config|c=s'	 => \$configPath,
           'help|h|?'	 => \&help,
	   'libpath|L=s' => \@libpath,
           'version|v'	 => \&version);
push @INC,@libpath;

require 'config.pl';
require 'opscript.pl';

sub help
{
print <<EOF;
Usage: $0 [<options>]

Migdal rating positions scanning script

  -c, --config=<path>       Set configuration file path
                            (default is `conf/migdal.conf')
  -L, --libpath=<path>      Look for libraries in <path>
                            (you can use this option many times)
  -h, --help                Print this help and exit
  -v, --version             Print version information and exit

Report bugs to <balu\@yes.ru>
EOF
exit;
}

sub version
{
print <<EOF;
ratings (migdal $VERSION)
Copyright (C) 2001 by Dmitry E. Melamud.

This program is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public
License (see COPYING).

EOF
exit;
}

sub init
{
readConfig();
$dbh=DBI->connect('DBI:mysql:database='.$Config{'dbName'}.';host='.
                  $Config{'dbHost'},$Config{'dbUser'},$Config{'dbPassword'},
		  {'AutoCommit' => 1,'PrintError' => 1,
		   'ShowErrorStatement' => 1});
}

sub scanJewishru
{
my (undef,$url)=@_;
my $pos=0;

for my $n (1..20)
    {
    open IN,"wget -qO - 'http://www.jewish.ru/topjews/index.asp?page=$n' |";
    my $pl=0;
    while(<IN>)
         {
	 $pl=$1 if /^<TR><TD class="TDITEM">(\d+)<\/TD>/;
         $pos=$pl,$pl=0 if /^<TD><dl><dt><A class="AITEM" HREF="$url/ && $pl!=0;
	 }
    close IN;
    last if $pos!=0;
    }
return (0,0,$pos,0);
}

sub scanMailru
{
my ($id,undef)=@_;
my ($td,$tw,$gd,$gw)=(0,0,0,0);

open IN,"wget -qO - 'http://top.mail.ru/stat?id=$id' |";
while(<IN>)
     {
     $td=$1 if /^<td><a href="\/Rating\/MassMedia-News\/Today\/Hosts\/\d*.html#(\d+)">/;
     $tw=$1 if /^<td><a href="\/Rating\/MassMedia-News\/Week\/Hosts\/\d*.html#(\d+)">/;
     $gd=$1 if /^<td><a href="\/Rating\/All\/Today\/Hosts\/\d*.html#(\d+)">/;
     $gw=$1 if /^<td><a href="\/Rating\/All\/Week\/Hosts\/\d*.html#(\d+)">/;
     }
close IN;
return ($td,$tw,$gd,$gw);
}

sub scanGoogleru
{
my ($id,undef)=@_;
my ($td,$tw)=(0,0);
my %pages=(''     => \$td,'24hho2' => \$td,'24hho3' => \$td,
           'who1' => \$tw,'who2'   => \$tw,'who3'   => \$tw);

while(my ($s,$var)=each(%pages))
    {
    open IN,"wget -qO - 'http://www.topcto.ru/other/index$s.html' |";
    my $pl=0;
    while(<IN>)
         {
	 $pl=$1 if /^\s*<font size="-1">&nbsp;(\d+)&nbsp;<\/font>\s*$/;
	 $$var=$pl,$pl=0 if /^\s*&nbsp;<a target=_blank title=".*href="http:\/\/www.topcto.ru\/cgi-bin\/click.cgi\?uid=$id.*class="go">.*<\/a>&nbsp;\s*$/ && $pl!=0;
	 }
    close IN;
    }
return ($td,$tw,0,0);
}

sub killNbsps
{
my ($s)=@_;

$s=~s/&nbsp;//g;
return $s;
}

sub scanRambler
{
my ($id,undef)=@_;
my ($td,$tw,$gd,$gw)=(0,0,0,0);

open IN,"wget -qO - 'http://top100.rambler.ru/cgi-bin/stats_top100.cgi?id=$id&page=6' |";
my $vd=\$td;
my $vw=\$tw;
my $sites=0;
while(<IN>)
     {
     $sites=1 if /^<tr bgcolor="#e0e0e0" align=right><td colspan=4 align=center><small><i>Рейтинг сайтов<\/i><\/small><\/td><\/tr>/;
     $$vd=killNbsps($1),$$vw=killNbsps($2),$vd=\$gd,$vw=\$gw,$sites=0 if /^<tr bgcolor="#f2f2f2" align=right><td><small>По посетителям<\/td><td><small>([^<]+)<font size="-2" color="#999999">&gt;&gt;<\/font><\/td><td><small>([^<]+)/ && $sites==1;
     }
close IN;
return ($td,$tw,$gd,$gw);
}

sub run
{
my $sth=$dbh->prepare('select id,ident,regid,url
                       from ratings');
$sth->execute;
while(my $rating=$sth->fetchrow_hashref)
     {
     my $name='scan'.ucfirst lc $rating->{'ident'};
     my ($td,$tw,$gd,$gw)=&{$name}($rating->{'regid'},$rating->{'url'});
     my $id=$rating->{'id'};
     $dbh->do("insert into rating_positions(rating_id,scan_date,topic_day,
                                            topic_week,global_day,global_week)
	       values($id,CURRENT_DATE(),$td,$tw,$gd,$gw)");
     }
}

sub done
{
$dbh->disconnect();
}

init();
run();
done();
